project_id = "bbtkxczusjblbuneyyyt"

[functions.analyze-food]
verify_jwt = true

[functions.payfast-checkout]
verify_jwt = true

[functions.payfast-itn]
verify_jwt = false

[functions.payfast-plan-purchase]
verify_jwt = true

[functions.sync-health-data]
verify_jwt = true
